more asterisk call patch-ing towards thread-safety
since @components might still fail - seeing nil values
as a hash entry gets removed (observed on JRuby 9.2)
```
NoMethodError: undefined method `call_ended' for nil:NilClass
	adhearsion/translator/asterisk/call.rb:345:in `block in
handle_hangup_event'
	org/jruby/RubyArray.java:1792:in `each'
```